{% set version = "0.5.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ttservice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ttservice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ttservice/ttservice_{{ version }}.tar.gz
  sha256: 1def82c6265d68b36866b83604a3901ddfa4677d907b11ed11c540a88c13f888

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-dplyr
    - r-plotly
  run:
    - r-base
    - r-matrix
    - r-dplyr
    - r-plotly

test:
  commands:
    - $R -e "library('ttservice')"           # [not win]
    - "\"%R%\" -e \"library('ttservice')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ttservice
  license: GPL-3.0-only
  summary: It provides generic methods that are used by more than one package, avoiding conflicts. This package will be imported by 'tidySingleCellExperiment' and 'tidyseurat'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ttservice
# Type: Package
# Title: A Service for Tidy Transcriptomics Software Suite
# Version: 0.2.2
# Authors@R: c(person("Stefano", "Mangiola", email = "mangiolastefano@gmail.com", role = c("aut", "cre")) )
# Description: It provides generic methods that are used by more than one package, avoiding conflicts. This package will be imported by 'tidySingleCellExperiment' and 'tidyseurat'.
# License: GPL-3
# Depends: R (>= 4.0.0)
# Imports: dplyr
# Suggests: methods
# Encoding: UTF-8
# RoxygenNote: 7.2.0
# NeedsCompilation: no
# Packaged: 2022-06-24 00:55:09 UTC; mangiola.s
# Author: Stefano Mangiola [aut, cre]
# Maintainer: Stefano Mangiola <mangiolastefano@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-06-24 06:50:02 UTC
